global using Microsoft.AspNetCore.Mvc;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Authorization;
global using MAM.Infrastructure;
global using MAM.Users;
global using MAM.Allergens.DTOs;
global using MediatR;
global using MAM.Allergens.Infrastructure;
global using MAM.Allergens.Domain;