// <auto-generated />
using System;
using MaterialAllergenManagementApp.Allergens.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaterialAllergenManagementApp.Allergens.Infrastructure.DatabaseMigrations
{
    [DbContext(typeof(AllergensDbContext))]
    [Migration("20230903110049_RenameMaterialAggregateAndCreateMaterialTypeAndCategory")]
    partial class RenameMaterialAggregateAndCreateMaterialTypeAndCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("allergens")
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3");

            modelBuilder.Entity("MaterialAllergenManagementApp.Allergens.Material", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllergenByCrossContamination")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllergenByNature")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Materials", "allergens");
                });

            modelBuilder.Entity("MaterialAllergenManagementApp.Allergens.MaterialType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicableFor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes", "allergens");

                    b.HasData(
                        new
                        {
                            Id = "748ca8d1-9eb3-430b-bea5-1e4ddf585819",
                            ApplicableFor = "RawMaterial;FinishedGood",
                            CreatedOn = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "6b8898cc-1ec3-4d7d-bd1c-e4d3890056ed",
                            ApplicableFor = "FinishedGood",
                            CreatedOn = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "c61e1dc8-c257-4796-8423-7815051e0ca8",
                            ApplicableFor = "PackagingMaterial",
                            CreatedOn = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "2cb9838e-8f77-4217-8558-55874ceef8cd",
                            ApplicableFor = "PackagingMaterial",
                            CreatedOn = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "9be1b154-8916-4ee7-9878-c00494fb01f1",
                            ApplicableFor = "RawMaterial;FinishedGood;PackagingMaterial",
                            CreatedOn = new DateTime(2023, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MaterialAllergenManagementApp.Allergens.Material", b =>
                {
                    b.HasOne("MaterialAllergenManagementApp.Allergens.MaterialType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
