name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker build . --file MAM.API/Dockerfile --tag mam-api:latest
  
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push mam-api:latest   

  deploy:
    needs: publish  
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set --name mam-api --resource-group material-allergen-management --docker-custom-image-name mam-api:latest
          az webapp restart --name mam-api --resource-group material-allergen-management
